version: '2'
services:
  mongodb:
    image: mongo:4.0.4
    restart: always
    container_name: mongo
    ports:
    - 27017:27017
  flask-service:
    image: mongo2
    build:
      context: ./flask 
    restart: always 
    container_name: flask 
    depends_on: 
      - mongodb
    ports:
      - 5000:5000
    environment: 
      - "MONGO_HOSTNAME=mongodb"
